### ISSUE TITLE
Cannot run on visual studio

### ISSUE THREAD

**Issue by qasawa** [QuantitativeBytes/qbRayTrace2#1]
Hello sir, I really appreciate your work and what great things you are doing.

I'm having a problem with running the repo in visual studio, there is no sln files so I can build it, any help?

**Comment by qasawa** [comment]
I just got it worked! but a problem appeared:
Failed to load image. Couldn't open testImage.bmp.
Any Idea sir?

**Comment by QuantitativeBytes** [comment]
I'm glad you got it working. You can use any bitmap image file in place of testImage.bmp, but it does have to have 4-bytes-per-pixel. This is actually a bug which has been pointed out to me and I will get around to fixing it as soon as I can. I think it must be a Visual Studio thing though, producing an error for this because the file is missing. When I compile using GCC in Linux, it doesn't mind the missing file because the class that uses the bitmap image is not actually used for anything. I will look into this a bit more. Like I say, I'll get to these issues as soon as I can, but it could take me a while... :-)
